name: clevros
dependencies:
- blas=1.1=openblas
- ca-certificates=2018.4.16=0
- certifi=2016.2.28=py35_0
- libgfortran=3.0.0=1
- ncurses=5.9=10
- numpy=1.14.2=py35_blas_openblas_200
- openblas=0.2.20=7
- openssl=1.0.2l=0
- pip=9.0.1=py35_1
- python=3.5.5=1
- readline=7.0=0
- setuptools=36.4.0=py35_1
- sqlite=3.20.1=0
- tk=8.6.6=0
- wheel=0.29.0=py35_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - frozendict==1.2
  - six==1.11.0

